content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: pubDate
        label: Publish Date
        type: date
      - name: description
        label: Description
        type: text
      - name: heroImage
        label: Cover Image
        type: image
      - name: body
        label: Body
        type: rich-text
    format: yaml-frontmatter

media: content/media
